# Build on top of base CentOS 9 Stream image
FROM quay.io/centos/arm64v8:stream9

# Create a non-root user
RUN useradd -ms /bin/bash tools

# Update container libraries and install tools available from the repos
RUN dnf -y update && \
    dnf install -y epel-release vim tar wget java-17-openjdk maven sudo gzip git rsync podman bash unzip openssh-clients ansible-core && \
    dnf clean all

# Install the latest version of OpenShift Do (odo)
RUN curl -L https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/v3.15.0/odo-linux-arm64 -o odo && \
    sudo install -o root -g root -m 0755 odo /usr/local/bin/odo

# Install the latest ArgoCD from the official Github repo
RUN VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/') && \
    curl -sSL -o argocd-linux-arm64 https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-arm64 && \
    sudo install -m 555 argocd-linux-arm64 /usr/local/bin/argocd && \
    rm argocd-linux-arm64

# Install the latest ArgoCD Autopilot from the official repo
RUN VERSION=$(curl --silent "https://api.github.com/repos/argoproj-labs/argocd-autopilot/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/') && \
    curl -L --output - https://github.com/argoproj-labs/argocd-autopilot/releases/download/"$VERSION"/argocd-autopilot-linux-arm64.tar.gz | tar zx && \
    chmod 555 argocd-autopilot-* && \
    mv ./argocd-autopilot-* /usr/local/bin/argocd-autopilot

# Install the latest Kubectl and OpenShift CLI tools
RUN mkdir /ocp-tools && \
    wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-arm64.tar.gz -P /ocp-tools && \
    cd /ocp-tools && \
    tar xvzf openshift-client-linux-arm64.tar.gz oc kubectl && \
    chmod 777 * && \
    mv oc kubectl /usr/local/bin

# Install the main hyperscaler clis
# Install the Azure cli
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
    dnf install -y azure-cli

# Install the AWS cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
    unzip -u awscliv2.zip && \
    sudo ./aws/install && \
    rm awscliv2.zip

# Install Terraform for ARM
RUN curl -O https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_arm64.zip && \
    unzip terraform_1.7.5_linux_arm64.zip && \
    sudo install -o root -g root -m 0755 terraform /usr/local/bin/terraform && \
    rm terraform_1.7.5_linux_arm64.zip

# Create directory for optional local storage mount
RUN mkdir -p /home/tools/local-storage && \
    chown -R tools:tools /home/tools/local-storage

# Switch to non-root user
USER tools

# Set WORKDIR to the location where the local storage will be mounted
WORKDIR /home/tools

CMD /bin/bash